#!/usr/bin/env php
<?php

/**
 * Merge a deployment override file into secrets.yml for the container.
 *
 * backend/secrets.yml is the shared configuration and is the file deploy.sh
 * uploads to the FTP host. A container cannot use it verbatim, because
 * "localhost" inside the php container is the php container itself rather than
 * the MariaDB service. The override file carries only the values that differ.
 *
 * The merge is a deep array merge, so an override may set a single nested key
 * without repeating the rest of the section. The result is written to a path
 * the Compose stack mounts as secrets.yml, leaving the real file untouched on
 * the host.
 *
 * Usage: php docker/merge-secrets.php <base> <override> <output>
 */

declare(strict_types=1);

use Symfony\Component\Yaml\Yaml;

require dirname(__DIR__) . '/vendor/autoload.php';

$arguments = array_slice($argv, 1, 3);
if (count($arguments) !== 3) {
    fwrite(STDERR, "Usage: merge-secrets.php <base> <override> <output>\n");
    exit(1);
}

[$basePath, $overridePath, $outputPath] = $arguments;

foreach ([$basePath, $overridePath] as $path) {
    if (!is_file($path) || !is_readable($path)) {
        fwrite(STDERR, "Unreadable configuration file: {$path}\n");
        exit(1);
    }
}

/**
 * Recursively merge $override into $base. Lists and scalars are replaced
 * rather than merged, because a partial list is never what an override means.
 */
$merge = static function (array $base, array $override) use (&$merge): array {
    foreach ($override as $key => $value) {
        if (is_array($value) && isset($base[$key]) && is_array($base[$key])
            && !array_is_list($value) && !array_is_list($base[$key])
        ) {
            $base[$key] = $merge($base[$key], $value);
            continue;
        }
        $base[$key] = $value;
    }

    return $base;
};

$base = Yaml::parseFile($basePath, Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE);
$override = Yaml::parseFile($overridePath, Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE);

if (!is_array($base) || !is_array($override)) {
    fwrite(STDERR, "Configuration files must contain YAML mappings.\n");
    exit(1);
}

$merged = $merge($base, $override);

$directory = dirname($outputPath);
if (!is_dir($directory) && !mkdir($directory, 0700, true) && !is_dir($directory)) {
    fwrite(STDERR, "Unable to create {$directory}\n");
    exit(1);
}

$yaml = "# Generated by docker/merge-secrets.php. Do not edit.\n"
    . "# Source: " . basename($basePath) . " + " . basename($overridePath) . "\n"
    . Yaml::dump($merged, 4, 2);

// Write through a temporary file so a reader never observes a partial config.
$temporary = $outputPath . '.tmp';
if (file_put_contents($temporary, $yaml, LOCK_EX) === false) {
    fwrite(STDERR, "Unable to write {$temporary}\n");
    exit(1);
}
chmod($temporary, 0444);
if (!rename($temporary, $outputPath)) {
    fwrite(STDERR, "Unable to publish {$outputPath}\n");
    exit(1);
}

fwrite(STDOUT, "Wrote {$outputPath}\n");
